## Mini-Project #0401

#### 필요한 패키지들을 불러온다:

In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.linear_model import LinearRegression

#### 데이터를 읽어온다:

In [2]:
os.chdir(r"C:\Users\bit\Desktop\20180717_머신러닝 알고리즘과 응용\data")

In [3]:
#df = pd.read_csv('data_kbo2015.csv', header='infer',encoding='ISO-8859-1')
df = pd.read_csv('data_kbo2015.csv', header='infer',encoding='latin1')

In [4]:
df.shape

(10, 26)

In [5]:
df

ranking     team    AVG    G    PA    AB    R     H   2B  3B  ...    IBB  \
0        1  Samsung  0.300  102  4091  3553  634  1066  188  19  ...     15   
1        2    Nexen  0.300  102  4151  3620  658  1085  227  12  ...     13   
2        3   Doosan  0.291   99  3950  3410  570   991  176  16  ...     17   
3        4       NC  0.288  101  3994  3485  591  1002  205  20  ...     17   
4        5    Lotte  0.277  104  4082  3557  545   985  176  14  ...     16   
5        6       SK  0.276   99  3888  3373  476   931  146   9  ...     12   
6        7   Hanhwa  0.270  102  4037  3404  504   919  162  13  ...     23   
7        8       kt  0.270  102  3988  3498  466   944  161  13  ...     13   
8        9       LG  0.259  103  3984  3491  458   905  171  16  ...     17   
9       10      KIA  0.256  100  3835  3362  469   861  161  14  ...     11   

   HBP   SO  GDP    SLG    OBP    OPS   MH   RISP  PH-BA  
0   47  650   78  0.471  0.374  0.845  101  0.300  0.216  
1   61  815   79  0.498  0.374  0.872  100  0.294  0.268  
2   66  544   95  0.438  0.368  0.806   98  0.284  0.262  
3   74  717   65  0.453  0.362  0.815  101  0.296  0.274  
4   57  866  105  0.444  0.356  0.800  104  0.272  0.190  
5   63  720   73  0.406  0.355  0.761   99  0.277  0.236  
6   86  780   78  0.397  0.360  0.757  102  0.264  0.196  
7   47  799   75  0.398  0.343  0.741  101  0.259  0.243  
8   57  803   68  0.389  0.334  0.723  103  0.238  0.231  
9   69  778   68  0.397  0.332  0.729  100  0.260  0.214  

[10 rows x 26 columns]

In [6]:
df.columns

Index(['ranking', 'team', 'AVG', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR',
       'TB', 'RBI', 'SAC', 'SF', 'BB', 'IBB', 'HBP', 'SO', 'GDP', 'SLG', 'OBP',
       'OPS', 'MH', 'RISP', 'PH-BA'],
      dtype='object')

In [7]:
X=np.array(df.H)
X=X.reshape(X.size,1)
Y=np.array(df.HR)
Y=Y.reshape(Y.size,1)

#### 선형회귀 적용:

In [8]:
lm = LinearRegression()

In [9]:
lm.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
lm.coef_

array([[0.28714054]])

In [11]:
lm.intercept_

array([-172.31047311])

#### 결정계수와 상관계수를 비교해 본다:

In [12]:
R2 = lm.score(X,Y)
R2

0.7029340148877057

In [13]:
corr = np.sqrt(R2)
corr

0.8384116023098116

In [14]:
np.corrcoef(X.T,Y.T)

array([[1.       , 0.8384116],
       [0.8384116, 1.       ]])

In [15]:
df.HR.corr(df.H)

0.8384116023098118