#### Numpy 행렬과 선형대수학:

In [8]:
import numpy as np

In [9]:
A = np.array([[1, 4, 6],[3, 7, 9]])
B = np.array([[7, 6],[3, 7]])
C = np.array([[1, 0],[3, 1],[2, 3]])

In [10]:
print(A)
print(B)
print(C)

[[1 4 6]
 [3 7 9]]
[[7 6]
 [3 7]]
[[1 0]
 [3 1]
 [2 3]]


In [11]:
A*B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
B*C

In [ ]:
A*C

In [12]:
A*np.transpose(C)

array([[ 1, 12, 12],
       [ 0,  7, 27]])

In [13]:
A.dot(B)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [14]:
B.dot(C)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [15]:
C.dot(A)

array([[ 1,  4,  6],
       [ 6, 19, 27],
       [11, 29, 39]])

내적 구하기:

In [16]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])

In [17]:
np.dot(x,y) #  44 = 1*2 + 3*4 + 5*6 

44

In [18]:
x.dot(y)

44

In [19]:
np.sum(x*y)

44

dot 연산자:

In [20]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
x = x.reshape((3,1))
y = y.reshape((1,3))
print(x)#"{}".format(x))
print(" ----------")
print(y)#"{}".format(y))

[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]


In [21]:
y.dot(x)[0,0]

44

In [22]:
x.dot(y)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

In [23]:
y*x

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

In [24]:
x*y

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

행렬 만들기

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.random.seed(222)
np.random.random([2,2])

array([[0.52602843, 0.68531719],
       [0.83567419, 0.65376526]])

In [28]:
np.random.seed(111)
np.random.randn(2,2)

array([[-1.13383833,  0.38431919],
       [ 1.49655378, -0.3553823 ]])

In [29]:
# 대각 행렬
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

행렬의 연산 (행렬과 행렬):

In [30]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])
m2 = np.array([[6, 5, 4],[3, 2, 1]])

In [31]:
m1+m2

array([[7, 7, 7],
       [7, 7, 7]])

In [32]:
m1*m2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [33]:
np.transpose(m2)

array([[6, 3],
       [5, 2],
       [4, 1]])

In [34]:
np.dot(m1,np.transpose(m2))

array([[28, 10],
       [73, 28]])

행렬의 연산 (행렬과 스칼라):

In [35]:
m = np.array([[1, 2],[3, 4]])

In [36]:
m*3

array([[ 3,  6],
       [ 9, 12]])

In [37]:
m/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [38]:
m+1

array([[2, 3],
       [4, 5]])

역행렬:

In [39]:
m = np.array([[1, 2],[3, 4]])
minv = np.linalg.inv(m)
minv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [40]:
mres = np.dot(m, minv)
mres
np.round(mres,2) 

array([[1., 0.],
       [0., 1.]])

연립 방정식: 이 경우에는 선형 방정식의 갯수 = 미지수의 갯수.

In [41]:
A = np.array([[5, 8],[6, 4]])
b = np.array([[30], [25]])
Ainv = np.linalg.inv(A)
print(np.dot(Ainv,b))

[[2.85714286]
 [1.96428571]]


In [42]:
np.linalg.solve(A, b)

array([[2.85714286],
       [1.96428571]])