#### Numpy 배열 만들기, 특성, 연산:

In [1]:
import numpy as np
np.__version__

'1.14.3'

In [2]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [3]:
arr3 = arr1

In [4]:
id(arr1)

2215346224784

In [5]:
id(arr3)

2215346224784

In [6]:
arr4 = arr1.copy()

In [7]:
id(arr4)

2215364754448

arange 메서드:

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [14]:
arr = np.arange(10) 

In [15]:
len(arr)

10

In [16]:
arr.size 

10

linspace 메서드:

In [41]:
np.linspace(1, 10, 5) 
# 1+((10-1)/4 * [0,1,2,3,4]) 
# 1+0 , 1+2.25*1 , 1+2.25*2 ... 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [42]:
arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [43]:
arr[0]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
arr[1]

2.5

zeros 메서드 & ones 메서드:

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0], dtype=int64)

In [48]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [50]:
arr = np.ones((2,3), dtype ='int_')

In [51]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
arr.dtype

dtype('int32')

원소의 자료형:

In [53]:
arr1 = np.array([111, 2.3,  True, False, False]) 
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [60]:
arr2 = np.array([111, 2., 'python', 'abc']) 
arr2

array(['111', '2.0', 'python', 'abc'], dtype='<U32')

In [63]:
arr3 = np.array([111, True, 'abc.']) 
arr3

array(['111', 'True', 'abc.'], dtype='<U11')

Numpy 배열의 슬라이싱 (slicing):

In [64]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [65]:
a[-1]

5

In [67]:
a[2:]

array([3, 4, 5])

In [68]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])

In [69]:
a[1]

array([4, 5, 6])

In [70]:
a[-1]

array([7, 8, 9])

Numpy 배열의 모양:

In [71]:
a.size

9

In [72]:
a.shape

(3, 3)

In [84]:
a.ndim

1

In [85]:
a = np.arange(15)
a.reshape(3,5) # 보여주기만 함. 마치 sorted() 처럼

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [91]:
a = a.reshape(4,1)
a

array([[2],
       [5],
       [1],
       [3]])

Numpy 배열 (조심):

In [92]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999

In [93]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [94]:
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

Numpy 로직 배열:

In [95]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 ) 
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [101]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

Numpy 배열의 확장:

In [102]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [103]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [104]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

Numpy 배열의 삭제:

In [105]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [106]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [107]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [108]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6]])