#### Numpy 배열의 연산:

리스트 연산과 Numpy 배열의 연산 비교:

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
a + a

[1, 2, 3, 1, 2, 3]

In [4]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
b = np.array([1, 2, 3])

In [6]:
b*3

array([3, 6, 9])

In [7]:
b + b

array([2, 4, 6])

In [8]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Numpy 배열의 연산:

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [10]:
a+b

array([5, 7, 9])

In [11]:
a-b

array([-3, -3, -3])

In [12]:
a*b

array([ 4, 10, 18])

In [13]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

연산의 벡터화:

In [14]:
x = np.array([0, 1, 2, 3])

In [15]:
pow(10, x)

array([   1,   10,  100, 1000], dtype=int32)

In [16]:
x**3

array([ 0,  1,  8, 27], dtype=int32)

In [17]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [18]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

메서드로 제공되는 통계함수:

In [19]:
x=np.arange(1,11)

In [20]:
x.sum()

55

In [21]:
x.mean()

5.5

In [23]:
x.std()

2.8722813232690143

In [24]:
x.var()

8.25

In [25]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [53]:
y = np.arange(1,10)
y = y.reshape((3,-1)) 
# 위와 같음. y.shape = (3,-1) 
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(y.mean(axis=0))

[4. 5. 6.]


In [55]:
print(y.mean(axis=1))

[2. 5. 8.]


In [80]:
np.random.seed(123)
z = np.random.randint(10,size=1000)

In [81]:
z.max()

9

In [82]:
z.min()

0

In [83]:
(z > 5).sum()

401

In [ ]:
np.unique(z)

In [ ]:
sorted(set(z))